// =========================================================
// 10X STOREFRONT — shared account / order / cart types
//
// These describe the shapes the UI renders. Mapping from the
// API's own shapes happens in components/account/
// AccountDataContext — one place, so components never handle
// raw API JSON.
// =========================================================

/* ----------------------------------------------------------- customer */

export type Customer = {
  id: string;
  name: string;
  email: string;
  phone: string;
  /** S3-backed profile picture URL. */
  avatarUrl?: string | null;
  /** ISO date the account was created — shown on the dashboard. */
  joinedAt: string;
};

/** What the signup form collects. */
export type SignupInput = {
  name: string;
  email: string;
  phone: string;
  password: string;
};

/* ------------------------------------------------------------ address */

export type Address = {
  id: string;
  /** Free-text label the customer picks: Home, Work, Mom's place. */
  label: string;
  fullName: string;
  phone: string;
  house: string;
  street: string;
  landmark?: string;
  city: string;
  state: string;
  pincode: string;
  /** Exactly one address is the default at any time. */
  isDefault: boolean;
};

/** A new address before it has an id. */
export type AddressDraft = Omit<Address, 'id'>;

/* -------------------------------------------------------------- order */

/**
 * Order lifecycle. The account order page renders a timeline from these, so
 * the order of the union is the order of the timeline.
 */
export const ORDER_STAGES = [
  'placed',
  'confirmed',
  'packed',
  'shipped',
  'out_for_delivery',
  'delivered',
] as const;

export type OrderStage = (typeof ORDER_STAGES)[number];

/** Terminal states that sit outside the happy path. */
export type OrderStatus = OrderStage | 'cancelled' | 'returned';

export const STAGE_LABEL: Record<OrderStage, string> = {
  placed: 'Order placed',
  confirmed: 'Confirmed',
  packed: 'Packed',
  shipped: 'Shipped',
  out_for_delivery: 'Out for delivery',
  delivered: 'Delivered',
};

export type PaymentMethod = 'online' | 'cod';

export type PaymentStatus = 'paid' | 'pending' | 'refunded' | 'failed';

export type OrderItem = {
  sku: string;
  name: string;
  packets: string;
  quantity: number;
  /** Unit price in rupees. */
  price: number;
};

export type OrderEvent = {
  stage: OrderStage;
  /** ISO timestamp, or null when the stage hasn't happened yet. */
  at: string | null;
  note?: string;
};

export type Order = {
  id: string;
  /** Human-facing reference — this is what appears in email and support. */
  reference: string;
  placedAt: string;
  status: OrderStatus;
  items: OrderItem[];
  subtotal: number;
  shipping: number;
  /** Coupon discount in rupees. 0 when no code was used. */
  discount: number;
  /** The code that produced `discount`, for the order summary and support. */
  couponCode?: string;
  total: number;
  paymentMethod: PaymentMethod;
  paymentStatus: PaymentStatus;
  address: Address;
  /** Full timeline, including stages not yet reached (`at: null`). */
  timeline: OrderEvent[];
  /** Set once shipped. */
  courier?: string;
  trackingNumber?: string;
  /** The courier's own status words, verbatim from Shiprocket. */
  courierStatus?: string;
  estimatedDelivery?: string;
  /** Present when this order was generated by a subscription cycle. */
  subscriptionId?: string;
};

/* ------------------------------------------------------- subscription */

export type SubscriptionStatus = 'active' | 'paused' | 'cancelled';

export type Subscription = {
  id: string;
  reference: string;
  sku: string;
  productName: string;
  packets: string;
  /** Charged each cycle, in rupees. */
  price: number;
  /** Human cadence label, e.g. "Every 4 weeks". */
  cadence: string;
  status: SubscriptionStatus;
  startedAt: string;
  /** ISO date of the next charge + dispatch. Null when paused or cancelled. */
  nextDelivery: string | null;
  /** How many cycles have shipped so far. */
  cyclesDelivered: number;
  address: Address;
  /** What the customer saves per cycle versus buying one-time. */
  savingsPerCycle: number;
  /** Auto-pay mandate state — '' means never set up. */
  autopayStatus: '' | 'initialized' | 'active' | 'paused' | 'cancelled' | 'failed';
  /** The customer chose pay-on-delivery — reminder emails stop. */
  autopayDeclined: boolean;
};

/* --------------------------------------------------------------- cart */

/**
 * The cart holds one configured line at a time — 10X sells a single product in
 * one pack size, so a multi-line cart would be scaffolding with nothing to
 * hold. Quantity lives on the line.
 */
export type CartLine = {
  /**
   * Catalogue ids. These are ALL the checkout sends about what is being
   * bought — the server looks the price up itself. A price in this object is
   * for display only; trusting one from the browser is a free discount
   * waiting to happen.
   */
  productId: string;
  tierId: string;
  sku: string;
  productName: string;
  tierName: string;
  packets: string;
  /** The product's own image, from the catalogue — used for cart thumbnails. */
  image: string;
  /** Its dark-look counterpart, when the catalogue has one. */
  imageDark?: string;
  /** Unit price for the chosen purchase type. */
  price: number;
  /** One-time purchases can scale; a subscription is always quantity 1. */
  quantity: number;
  isSubscription: boolean;
  /** One-time list price, kept so the cart can show subscription savings. */
  oneTimePrice: number;
  /** Units the warehouse actually has, so the quantity picker can't oversell. */
  stock?: number;
};

/* -------------------------------------------------------------- money */

export function inr(n: number) {
  return `₹${n.toLocaleString('en-IN')}`;
}

/**
 * Shipping.
 *
 * The threshold and the flat rate are store settings, read from the API — this
 * only applies them. There is deliberately no default: a cart that promises
 * free delivery the checkout then charges for is worse than one that waits a
 * beat to say. Callers pass the fetched values, and hold the line until they
 * have them (see `settingsLoaded` on the cart).
 */
export function shippingFor(
  subtotal: number,
  freeOver: number,
  flat: number,
  mode: 'free' | 'priced' = 'priced',
) {
  if (mode === 'free') return 0;
  return subtotal >= freeOver ? 0 : flat;
}
